# This is a basic workflow to help you get started with Actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_and_build:
    name: Test and Build
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29]

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Set Up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Upload Unit Test Reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v1
        with:
          name: unit_test_reports
          path: app/build/reports

      - name: Run Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          profile: pixel_4
          emulator-options: -no-window -no-snapshot -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back emulated -timezone Europe/London -memory 2048
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest

      - name: Upload Instrumented Test Reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v1
        with:
          name: instrumented_test_reports
          path: app/build/reports

      - name: Upload Debug APK
        uses: actions/upload-artifact@v1
        with:
          name: TasksDemoDebug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
